// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/dead_letter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeadLetterMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalId     string                 `protobuf:"bytes,1,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`
	OriginalTopic  string                 `protobuf:"bytes,2,opt,name=original_topic,json=originalTopic,proto3" json:"original_topic,omitempty"`
	FailedAt       int64                  `protobuf:"varint,3,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	ErrorReason    string                 `protobuf:"bytes,4,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	OriginalValues []byte                 `protobuf:"bytes,5,opt,name=original_values,json=originalValues,proto3" json:"original_values,omitempty"`
	OriginalHeader map[string]string      `protobuf:"bytes,6,rep,name=original_header,json=originalHeader,proto3" json:"original_header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source         string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeadLetterMessage) Reset() {
	*x = DeadLetterMessage{}
	mi := &file_proto_dead_letter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetterMessage) ProtoMessage() {}

func (x *DeadLetterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dead_letter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetterMessage.ProtoReflect.Descriptor instead.
func (*DeadLetterMessage) Descriptor() ([]byte, []int) {
	return file_proto_dead_letter_proto_rawDescGZIP(), []int{0}
}

func (x *DeadLetterMessage) GetOriginalId() string {
	if x != nil {
		return x.OriginalId
	}
	return ""
}

func (x *DeadLetterMessage) GetOriginalTopic() string {
	if x != nil {
		return x.OriginalTopic
	}
	return ""
}

func (x *DeadLetterMessage) GetFailedAt() int64 {
	if x != nil {
		return x.FailedAt
	}
	return 0
}

func (x *DeadLetterMessage) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *DeadLetterMessage) GetOriginalValues() []byte {
	if x != nil {
		return x.OriginalValues
	}
	return nil
}

func (x *DeadLetterMessage) GetOriginalHeader() map[string]string {
	if x != nil {
		return x.OriginalHeader
	}
	return nil
}

func (x *DeadLetterMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_proto_dead_letter_proto protoreflect.FileDescriptor

const file_proto_dead_letter_proto_rawDesc = "" +
	"\n" +
	"\x17proto/dead_letter.proto\x12\x05proto\"\xf6\x02\n" +
	"\x11DeadLetterMessage\x12\x1f\n" +
	"\voriginal_id\x18\x01 \x01(\tR\n" +
	"originalId\x12%\n" +
	"\x0eoriginal_topic\x18\x02 \x01(\tR\roriginalTopic\x12\x1b\n" +
	"\tfailed_at\x18\x03 \x01(\x03R\bfailedAt\x12!\n" +
	"\ferror_reason\x18\x04 \x01(\tR\verrorReason\x12'\n" +
	"\x0foriginal_values\x18\x05 \x01(\fR\x0eoriginalValues\x12U\n" +
	"\x0foriginal_header\x18\x06 \x03(\v2,.proto.DeadLetterMessage.OriginalHeaderEntryR\x0eoriginalHeader\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x1aA\n" +
	"\x13OriginalHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\"Z github.com/nilorg/eventbus/protob\x06proto3"

var (
	file_proto_dead_letter_proto_rawDescOnce sync.Once
	file_proto_dead_letter_proto_rawDescData []byte
)

func file_proto_dead_letter_proto_rawDescGZIP() []byte {
	file_proto_dead_letter_proto_rawDescOnce.Do(func() {
		file_proto_dead_letter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dead_letter_proto_rawDesc), len(file_proto_dead_letter_proto_rawDesc)))
	})
	return file_proto_dead_letter_proto_rawDescData
}

var file_proto_dead_letter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dead_letter_proto_goTypes = []any{
	(*DeadLetterMessage)(nil), // 0: proto.DeadLetterMessage
	nil,                       // 1: proto.DeadLetterMessage.OriginalHeaderEntry
}
var file_proto_dead_letter_proto_depIdxs = []int32{
	1, // 0: proto.DeadLetterMessage.original_header:type_name -> proto.DeadLetterMessage.OriginalHeaderEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dead_letter_proto_init() }
func file_proto_dead_letter_proto_init() {
	if File_proto_dead_letter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dead_letter_proto_rawDesc), len(file_proto_dead_letter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dead_letter_proto_goTypes,
		DependencyIndexes: file_proto_dead_letter_proto_depIdxs,
		MessageInfos:      file_proto_dead_letter_proto_msgTypes,
	}.Build()
	File_proto_dead_letter_proto = out.File
	file_proto_dead_letter_proto_goTypes = nil
	file_proto_dead_letter_proto_depIdxs = nil
}
